version: "3.8"

services:
  app:
    image: counter-app:latest

    # Переменные окружения
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    # Публикация портов в Swarm
    ports:
      - target: 8000
        published: 80
        protocol: tcp
        mode: ingress

    networks:
      - app-network

    # Конфигурация развертывания в Swarm
    deploy:
      replicas: 4
      restart_policy:
        condition: any

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

# Overlay-сеть для связи между сервисами в разных нодах
networks:
  app-network:
    driver: overlay

# Том для данных Redis
volumes:
  redis-data:
    driver: local
